### ISSUE TITLE
I am not able to make it work please help!

### ISSUE THREAD

**Issue by LMeiraba** [aDu/pet-pet-gif#3]

**Comment by aDu** [comment]
I need more info. Do the Eris examples not work?

Have you tried debugging with just an avatar URL? I do not use other Discord JS wrappers.

Join the Discord from the repo's readme and I will take a look (will be busy at work so may be unresponsive).

**Comment by aDu** [comment]
This works on my servers and locally.

It would help if you paste the error message as well as the code snippet that caused the error, otherwise nobody will be able to diagnose your problem. Also providing the Node version as well as the pet-pet-gif version you installed would help.

Only posting "I am not able to make it work please help!" and not providing any other information is not really helpful >_>.

Thanks in advance.
